### PR TITLE
Updating R CMD check Actions

### PR DESCRIPTION
**Pull request by MowahidLatif**
Please wait until confirmation of merger. Waiting for proper checks to pass. Referencing previous errors with current errors for proper diagnoses of issue.

### CODE REVIEW

**Comment by MowahidLatif** [comment]
Please merge this branch. Everything is in order.

**Comment by MowahidLatif** [comment]
2 Attempts were made and both resulted in failure. I assume it is because of all the previous errors in the R-CMD-check. I have checked and they go back at least 8+ months.

**Review by aylapear — CHANGES_REQUESTED** [review]
The badge thing. Need to switch R-CMD-check for R build status.

**Comment by MowahidLatif** [comment]
Although there are errors listed, the comment above says they are acceptable. With that said, please merge this branch. Everything is in order.

**Comment by aylapear** [comment]
checks have been failing for a long time, merging as updating actions not changing any code

**Pull request merged**
